apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argo-cd
spec:
  project: integration
  source:
    targetRevision: HEAD
    path: dev/integration/svc/kafka
    repoURL: 'git@github.com:kovpetest/argo-cd.git'
  destination:
    namespace: integration
    server: https://AC6DAE4C00F8C829F8B2F66F7DC2282C.gr7.eu-central-1.eks.amazonaws.com
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
