apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: sbx-dev
  source:
    repoURL: git@github.com:kovpetest/argo-cd.git
    path: dev/sbx/svc/redis
    targetRevision: HEAD
  destination:
    namespace: sbx-2
    server: https://AC6DAE4C00F8C829F8B2F66F7DC2282C.gr7.eu-central-1.eks.amazonaws.com
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
